name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama principal de tu repositorio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Cambia según la versión que uses

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Construir el proyecto
      - name: Build the project
        run: npm run build

      # 5. Deploy a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist
