name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama principal de tu repositorio si es diferente.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # O la versión que uses en tu proyecto

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Generar archivos estáticos
      - name: Build and export static site
        run: npm run export

      # 5. Subir a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
